### ISSUE TITLE
No module named 'ffxivbot'

### ISSUE THREAD

**Issue by Ericwww** [Bluefissure/FFXIVBOT#4]
装完依赖包后 把代码clone到本地然后 打开shell 输入
`python manage.py makemigrations`
提示

```Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Program Files\Python36-32\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "D:\Program Files\Python36-32\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "D:\Program Files\Python36-32\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\Program Files\Python36-32\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "D:\Program Files\Python36-32\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "D:\Program Files\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ffxivbot'```

**Comment by Ericwww** [comment]
想问下是打开方式不对吗xxx

**Comment by MYuuuuuu** [comment]
python manage.py makemigrations ffxivbot
即可
